//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hylasoft.Services.Resources {
  /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hylasoft.Services.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitored data tag &apos;{0}&apos; has changed from &apos;{1}&apos; to &apos;{2}&apos;..
        /// </summary>
        internal static string DataMonitoringServiceTagChanged {
            get {
                return ResourceManager.GetString("DataMonitoringServiceTagChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data monitoring has started..
        /// </summary>
        internal static string DataMonitoringStarted {
            get {
                return ResourceManager.GetString("DataMonitoringStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data monitoring has been halted..
        /// </summary>
        internal static string DataMonitoringStopped {
            get {
                return ResourceManager.GetString("DataMonitoringStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling data monitored method &apos;{0}&apos;..
        /// </summary>
        internal static string MonitoringServiceMethodCalled {
            get {
                return ResourceManager.GetString("MonitoringServiceMethodCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring method &apos;{0}&apos; loaded..
        /// </summary>
        internal static string MonitorMethodRead {
            get {
                return ResourceManager.GetString("MonitorMethodRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully parsed schedule method &apos;{0}&apos; on interval &apos;{1}&apos;..
        /// </summary>
        internal static string ScheduleMethodRead {
            get {
                return ResourceManager.GetString("ScheduleMethodRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling scheduled method &apos;{0}&apos;..
        /// </summary>
        internal static string ScheduleServiceMethodCalled {
            get {
                return ResourceManager.GetString("ScheduleServiceMethodCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} successfully continued..
        /// </summary>
        internal static string ServiceContinued {
            get {
                return ResourceManager.GetString("ServiceContinued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} successfully initialized..
        /// </summary>
        internal static string ServiceInitialized {
            get {
                return ResourceManager.GetString("ServiceInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} successfully paused..
        /// </summary>
        internal static string ServicePaused {
            get {
                return ResourceManager.GetString("ServicePaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} successfully started..
        /// </summary>
        internal static string ServiceStarted {
            get {
                return ResourceManager.GetString("ServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} transitioned to status {1}..
        /// </summary>
        internal static string ServiceStatusChanged {
            get {
                return ResourceManager.GetString("ServiceStatusChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} successfully stopped..
        /// </summary>
        internal static string ServiceStopped {
            get {
                return ResourceManager.GetString("ServiceStopped", resourceCulture);
            }
        }
    }
}
